name: Azure ARM

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

# Special permissions required for OIDC authentication
permissions:
  id-token: write
  actions: read
  contents: read
  pull-requests: write
  security-events: write

jobs:
  bicep-linter:
    name: 'Bicep Linter'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Bicep linter
        run: az bicep build --file main.bicep

  bicep-validate:
    name: 'Bicep Validate'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: azure/arm-deploy@v1
        name: Run preflight validation
        with:
          deploymentName: ${{ github.run_number }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./main.bicep
          deploymentMode: Validate

  bicep-deploy:
    name: 'Bicep Deploy'
    needs: [bicep-validate, bicep-linter]
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@main
      # Log into Azure
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy Bicep file
      - name: Deploy Bicep template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./main.bicep
          failOnStdErr: false